{% set name = "sdv" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdv-{{ version }}.tar.gz
  sha256: 74ef5baafa7c0e39d073a7e066c92af5be0573ffa27a92158d242fb7143fe2a5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.7,<3.11
  run:
    - boto3>=1.15.0,<2
    - botocore>=1.18,<2
    - cloudpickle >=2.1.0,<3.0
    - copulas >=0.8.0,<0.9
    - ctgan >=0.7.1,<0.8
    - deepecho >=0.4.0,<0.5
    - faker >=10.0.0,<15
    - python-graphviz >=0.13.2,<1
    - numpy >=1.20.0,<2
    - pandas >=1.1.3,<2
    - python >=3.7,<3.11
    - rdt >=1.3.0,<2
    - sdmetrics >=0.9.1,<0.10
    - tqdm >=4.15,<5

test:
  imports:
    - sdv
    - sdv.constraints
  requires:
    - pip


about:
  home: https://github.com/sdv-dev/SDV
  summary: Synthetic Data Generation for tabular, relational and time series data.
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amontanez24
    - fealho
    - frances-h
    - pvk-developer
