{% set name = "sdv" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdv-{{ version }}.tar.gz
  sha256: 60752a6db799a2816a1dbdfc4869fb3fa27920361f750b34b68f76890e447cc7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.8,<3.12
  run:
    - boto3 >=1.15.0,<2
    - botocore >=1.18,<2
    - cloudpickle >=2.1.0,<3.0
    - copulas >=0.9.0,<0.10
    - ctgan >=0.7.4,<0.8
    - deepecho >=0.4.2,<0.5
    - faker >=10.0.0,<15
    - python-graphviz >=0.13.2,<1
    - numpy >=1.20.0,<1.25.0
    - pandas >=1.1.3
    - python >=3.8,<3.12
    - rdt >=1.7.0,<2
    - sdmetrics >=0.11.0,<0.12
    - tqdm >=4.15,<5

test:
  imports:
    - sdv
    - sdv.constraints
  requires:
    - pip


about:
  home: https://github.com/sdv-dev/SDV
  summary: Synthetic Data Generation for tabular, relational and time series data.
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amontanez24
    - fealho
    - frances-h
    - pvk-developer
