{% set name = "sdv" %}
{% set version = "1.17.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdv-{{ version }}.tar.gz
  sha256: c844e0a1728b5bfc18586db07e834051463bc3f610cbcc40d24c3f3b01b66525

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.8,<3.13
    - setuptools
  run:
    - boto3 >=1.28.0,<2
    - botocore >=1.31,<2
    - cloudpickle >=2.1.0
    - copulas >=0.11.0
    - ctgan >=0.10.0
    - deepecho >=0.6.0
    - python-graphviz >=0.13.2
    - numpy >=1.21.0,<2
    - pandas >=1.4.0
    - platformdirs >=4.0
    - python >=3.8,<3.13
    - pyyaml >=6.0.1
    - rdt >=1.12.3
    - sdmetrics >=0.16.0
    - tqdm >=4.29

test:
  imports:
    - sdv
    - sdv.constraints
  requires:
    - pip


about:
  home: https://github.com/sdv-dev/SDV
  summary: Synthetic Data Generation for tabular, relational and time series data.
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amontanez24
    - fealho
    - frances-h
    - lajohn4747
    - pvk-developer
    - rwedge
    - gsheni
    - R-Palazzo
