{% set name = "sdv" %}
{% set version = "0.17.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdv-{{ version }}.tar.gz
  sha256: 61b159622a6eaef4b3c5c1f0e95e0ed1eb207b3d5a0ccb1043d73c3d22811104

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.6,<3.10
  run:
    - copulas >=0.7.0,<0.8
    - ctgan >=0.5.2,<0.6
    - deepecho >=0.3.0.post1,<0.4
    - faker >=10.0.0,<15
    - python-graphviz >=0.13.2,<1
    - numpy >=1.18.0,<2
    - pandas >=1.1.3,<2
    - python >=3.6,<3.10
    - rdt >=1.2.0,<1.3
    - sdmetrics >=0.6.0,<0.7
    - tqdm >=4.15,<5
    - cloudpickle >=2.1.0,<3.0

test:
  imports:
    - sdv
    - sdv.constraints
  requires:
    - pip


about:
  home: https://github.com/sdv-dev/SDV
  summary: Synthetic Data Generation for tabular, relational and time series data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amontanez24
    - csala
    - fealho
    - katxiao
    - pvk-developer
