{% set name = "sdv" %}
{% set version = "0.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdv-{{ version }}.tar.gz
  sha256: 58e26fa38a719f231d7b3823c5a350a7e74417e2341ac1023e9e67542b0c5265

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.6,<3.10
  run:
    - copulas >=0.7.0,<0.8
    - ctgan >=0.5.1,<0.6
    - deepecho >=0.3.0.post1,<0.4
    - faker >=3.0.0,<10
    - python-graphviz >=0.13.2,<1
    - numpy >=1.18.0,<2
    - pandas >=1.1.3,<2
    - python >=3.6,<3.10
    - rdt >=0.6.2,<0.7
    - sdmetrics >=0.5.0,<0.6
    - tqdm >=4.15,<5

test:
  imports:
    - sdv
    - sdv.constraints
  requires:
    - pip


about:
  home: https://github.com/sdv-dev/SDV
  summary: Synthetic Data Generation for tabular, relational and time series data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amontanez24
    - csala
    - fealho
    - katxiao
    - pvk-developer
