{% set name = "sdv" %}
{% set version = "1.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sdv-{{ version }}.tar.gz
  sha256: 47bbccbcf235475de1f2b965550d69a659a248ea1baa806b251f32180009ec0b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python {{ python_min }}
    - setuptools
  run:
    - boto3 >=1.28.0,<2
    - botocore >=1.31,<2
    - cloudpickle >=2.1.0
    - copulas >=0.12.0
    - ctgan >=0.10.2
    - deepecho >=0.6.1
    - python-graphviz >=0.13.2
    - numpy >=1.21.0,<2
    - pandas >=1.4.0
    - platformdirs >=4.0
    - python >={{ python_min }},<3.13
    - pyyaml >=6.0.1
    - rdt >=1.13.2
    - sdmetrics >=0.17.0
    - tqdm >=4.29

test:
  imports:
    - sdv
    - sdv.constraints
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://github.com/sdv-dev/SDV
  summary: Synthetic Data Generation for tabular, relational and time series data.
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amontanez24
    - fealho
    - frances-h
    - lajohn4747
    - pvk-developer
    - rwedge
    - gsheni
    - R-Palazzo
