{% set name = "sdv" %}
{% set version = "1.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdv-{{ version }}.tar.gz
  sha256: a79443521d8cb28c056ff147791bba91712cdf573404cacd93c077fce98e4f29

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.8,<3.12
  run:
    - boto3 >=1.15.0,<2
    - botocore >=1.18,<2
    - cloudpickle >=2.1.0,<3.0
    - copulas >=0.9.0,<0.10
    - ctgan >=0.9.0,<0.10
    - deepecho >=0.5.0,<0.6
    - python-graphviz >=0.13.2,<1
    - numpy >=1.20.0,<2
    - pandas >=1.1.3
    - python >=3.8,<3.12
    - rdt >=1.10.0,<2
    - sdmetrics >=0.13.0,<0.14
    - tqdm >=4.15,<5

test:
  imports:
    - sdv
    - sdv.constraints
  requires:
    - pip


about:
  home: https://github.com/sdv-dev/SDV
  summary: Synthetic Data Generation for tabular, relational and time series data.
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amontanez24
    - fealho
    - frances-h
    - lajohn4747
    - pvk-developer
    - rwedge
